export const PropertiesConfig = {
    alreadyDeleted: 'Propiedad ya eliminada',
    amountError: 'La cantidad debe ser un número mayor a cero',
    deleted: 'Propiedad eliminada',
    errorDeletingImages: 'Error al eliminar imágenes',
    errorRestoringImages: 'Error al restaurar imágenes',
    integerError: 'La cantidad debe ser un número entero',
    notCreated: 'Propiedad no creada',
    notDeleted: 'Propiedad no eliminada',
    notDeletedErrorImages: 'Propiedad no eliminada. Error al eliminar imágenes',
    notFound: 'Propiedad no encontrada',
    notFoundMany: 'Propiedades no encontradas',
    notRestored: 'Propiedad no restaurada',
    notUpdated: 'Propiedad no actualizada',
    ownerRequired: 'No tienes permisos para eliminar la propiedad',
    restoredWithImages: 'Propiedad restaurada (con imágenes)',
    restoredWithoutImages: 'Propiedad restaurada (sin imágenes)',
    updated: 'Propiedad actualizada',
    userNotFound: 'Usuario no encontrado',
}